name: R08IPhoneSample
options:
  minimumXcodeGenVersion: 2.40.0
  deploymentTarget:
    iOS: "16.0"
packages:
  Core:
    path: ./Packages/Core
  SmartRingCommunicationModule:
    path: ./Packages/SmartRingCommunicationModule
targets:
  R08IPhoneSample:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App/Sources/App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.halliday.sample.r08
        PRODUCT_NAME: R08IPhoneSample
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: App/Sources/App/Support/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
    dependencies:
      - package: Core
        product: Core
      - package: SmartRingCommunicationModule
        product: SmartRingCommunicationModule
schemes:
  R08IPhoneSample:
    build:
      targets:
        R08IPhoneSample: all
    run:
      config: Debug
    archive:
      config: Release
